# Exemple : Déploiement Sylius en Recette
name: Deploy Sylius Recette

on:
  push:
    branches: [env/recette]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: recette
      url: https://recette-monprojet-sylius.dediagency.dev

    steps:
      - name: Deploy to recette
        uses: dediagency/.github/actions/deploy@v0
        with:
          ssh_host: preprod.dediagency.net
          ssh_username: monprojet-sylius
          environment: recette
          branch: env/recette
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

          # Optionnel : surcharger les defaults
          # permission_method: setfacl
          # setfacl_user: www-data
          # setfacl_group: www-data
