#!/bin/bash

config_require_base() {
    : "${DEPLOY_ENVIRONMENT:?DEPLOY_ENVIRONMENT is required}"
    : "${DEPLOY_BRANCH:?DEPLOY_BRANCH is required}"
    : "${DEPLOY_SSH_USERNAME:?DEPLOY_SSH_USERNAME is required}"
    : "${DEPLOY_REPOSITORY:?DEPLOY_REPOSITORY is required}"
}

config_apply_base_defaults() {
    DEPLOY_PHP_VERSION=${DEPLOY_PHP_VERSION:-8.3}
    DEPLOY_PHP_BINARY=${DEPLOY_PHP_BINARY:-php8.3}
    DEPLOY_COMPOSER_PATH=${DEPLOY_COMPOSER_PATH:-/usr/bin/composer}
    DEPLOY_NODE_BINARY=${DEPLOY_NODE_BINARY:-node}
    DEPLOY_NPM_BINARY=${DEPLOY_NPM_BINARY:-npm}
    DEPLOY_PERMISSION_METHOD=${DEPLOY_PERMISSION_METHOD:-chmod}
    DEPLOY_FILE_PERMISSIONS=${DEPLOY_FILE_PERMISSIONS:-755}
    DEPLOY_VAR_PERMISSIONS=${DEPLOY_VAR_PERMISSIONS:-775}
    DEPLOY_RUN_POST_DEPLOY_CMD=${DEPLOY_RUN_POST_DEPLOY_CMD:-true}
    DEPLOY_COMPOSER_INSTALL_ARGS=${DEPLOY_COMPOSER_INSTALL_ARGS:--no-dev --optimize-autoloader --no-interaction --no-scripts}
    DEPLOY_DRY_RUN=${DEPLOY_DRY_RUN:-false}

    if [ -z "${DEPLOY_DEPLOY_PATH:-}" ]; then
        DEPLOY_DEPLOY_PATH="$HOME/${DEPLOY_ENVIRONMENT}-${DEPLOY_SSH_USERNAME}"
    fi

    if [ -z "${DEPLOY_SITE_URL:-}" ]; then
        DEPLOY_SITE_URL="https://${DEPLOY_ENVIRONMENT}-${DEPLOY_SSH_USERNAME}.dediagency.dev"
    fi

    if [ -z "${DEPLOY_APP_ENV:-}" ]; then
        case "${DEPLOY_ENVIRONMENT}" in
            recette)
                DEPLOY_APP_ENV="staging"
                ;;
            preproduction|preprod)
                DEPLOY_APP_ENV="staging"
                ;;
            production|prod)
                DEPLOY_APP_ENV="prod"
                ;;
        esac
    fi

    if [ "${DEPLOY_NPM_INSTALL_COMMAND}" = "skip" ] || [ "${DEPLOY_NPM_INSTALL_COMMAND}" = "none" ]; then
        DEPLOY_NPM_INSTALL_COMMAND=""
    fi

    if [ "${DEPLOY_BUILD_COMMAND}" = "skip" ] || [ "${DEPLOY_BUILD_COMMAND}" = "none" ]; then
        DEPLOY_BUILD_COMMAND=""
    fi
}

config_export_envs() {
    export \
        DEPLOY_ENVIRONMENT DEPLOY_BRANCH DEPLOY_SSH_USERNAME DEPLOY_PLATFORM \
        DEPLOY_PHP_VERSION DEPLOY_PHP_BINARY DEPLOY_COMPOSER_PATH DEPLOY_NODE_BINARY \
        DEPLOY_NPM_BINARY DEPLOY_REPOSITORY DEPLOY_PERMISSION_METHOD DEPLOY_FILE_PERMISSIONS \
        DEPLOY_VAR_PERMISSIONS DEPLOY_SETFACL_USER DEPLOY_SETFACL_GROUP DEPLOY_RUN_POST_DEPLOY_CMD \
        DEPLOY_DEPLOY_PATH DEPLOY_SITE_URL DEPLOY_APP_ENV DEPLOY_DB_OPERATIONS \
        DEPLOY_CACHE_COMMANDS DEPLOY_ASSET_COMMANDS DEPLOY_SHARED_DIRS DEPLOY_SHARED_FILES \
        DEPLOY_RELOAD_SERVICES DEPLOY_POST_DEPLOY_COMMANDS DEPLOY_NPM_INSTALL_COMMAND \
        DEPLOY_BUILD_COMMAND DEPLOY_COMPOSER_INSTALL_ARGS DEPLOY_DRY_RUN
}
